[tools]
python = "3.12"

[env]
_.path = ["bin"]
_.python.venv = { path = ".venv", create = true, python = "3.12", uv_create_args = ["--prompt", "epub2audio"] }
# _.source = ".venv/bin/activate"

[task_config]
dir = "bin"

[tasks.build]
description = "Build the project"
run = "uv build"

[tasks.format]
description = "Format code with ruff"
run = "ruff format ."

[tasks.lint]
description = "Lint code with ruff"
run = "ruff check ."

[tasks.fix]
description = "Fix auto-fixable issues with ruff"
run = "ruff check --fix ."

[tasks.test]
description = "Run tests"
run = "pytest"
depends = ["format", "lint", "fix"]

[tasks.test-integration]
description = "Run integration tests"
run = "pytest --run-integration"
depends = ["test"]

[tasks.test-coverage]
description = "Run tests with coverage report"
run = "pytest --cov=src tests/" 
depends = ["test"]